version: '3.8'
volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  web:
    image: irinabalerina/yamdb_final:latest
    restart: always
    depends_on:
      - db
    command: python manage.py python manage.py migrate --noinput
    python manage.py createsuperuser
    python manage.py loaddata fixtures.json
    python manage.py collectstatic --no-input
    env_file:
      - ./.env
    volumes:
      - static:/code/static/
      - media:/code/media/

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - static:/var/html/static
      - media:/var/html/media
    depends_on:
      - web
    env_file:
      - ./.env
    ports:
      - "80:80"
